version: 2

models:
  - name: call_center_model
    columns:
      - name: CC_CALL_CENTER_ID
        tests:
          - not_null

      - name: CC_NAME
        tests:
          - not_null

      - name: CC_EMPLOYEES
        tests:
          - not_null
